server:
  port: 5000

app:
  name: detourservice

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://detourdata:planejanes@docdb-2020-06-12-23-50-39.cluster-cg7wesluoa8o.us-east-1.docdb.amazonaws.com:27017/detourdb?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false