server:
  port: 5000

app:
  name: detourservice

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: cluster0-3m8d0.mongodb.net
      port: 27017
      username: anandhi
      password: test1234
      database: detourDB
      
      