server:
  port: 5000

app:
  name: detourservice

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: docdb-2020-06-13-00-44-24.cluster-cg7wesluoa8o.us-east-1.docdb.amazonaws.com
      port: 27017
      username: detourdata
      password: planejanes
      database: detourdb
      
      